remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

include:
  - .htaccess
  - _pages
  - assets/css/custom.css

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail:
    before: 2
    after: 2

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

locale: "en-US"
title: "🏦 THE UROGYN VAULT"
words_per_minute: 200

author:
  name: "Your Name"
  bio: "I am an **amazing** person."
  location: "Somewhere"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
  since: "2025"
