name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install dependencies
        run: |
          gem install bundler jekyll
      - name: Build site
        run: |
          jekyll build
